// Mocks generated by Mockito 5.4.6 from annotations
// in restaurant_app/test/list_restaurant_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_app/core/response/add_review_response.dart' as _i5;
import 'package:restaurant_app/core/response/detail_restaurant_response.dart'
    as _i3;
import 'package:restaurant_app/core/response/list_restaurants_response.dart'
    as _i2;
import 'package:restaurant_app/core/response/search_restaurant_response.dart'
    as _i4;
import 'package:restaurant_app/core/service/api_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeListRestaurantsResponse_0 extends _i1.SmartFake
    implements _i2.ListRestaurantsResponse {
  _FakeListRestaurantsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDetailRestaurantResponse_1 extends _i1.SmartFake
    implements _i3.DetailRestaurantResponse {
  _FakeDetailRestaurantResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchRestaurantResponse_2 extends _i1.SmartFake
    implements _i4.SearchRestaurantResponse {
  _FakeSearchRestaurantResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddReviewResponse_3 extends _i1.SmartFake
    implements _i5.AddReviewResponse {
  _FakeAddReviewResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i6.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.ListRestaurantsResponse> getListRestaurants() =>
      (super.noSuchMethod(
            Invocation.method(#getListRestaurants, []),
            returnValue: _i7.Future<_i2.ListRestaurantsResponse>.value(
              _FakeListRestaurantsResponse_0(
                this,
                Invocation.method(#getListRestaurants, []),
              ),
            ),
          )
          as _i7.Future<_i2.ListRestaurantsResponse>);

  @override
  _i7.Future<_i3.DetailRestaurantResponse> getDetailRestaurant(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getDetailRestaurant, [id]),
            returnValue: _i7.Future<_i3.DetailRestaurantResponse>.value(
              _FakeDetailRestaurantResponse_1(
                this,
                Invocation.method(#getDetailRestaurant, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.DetailRestaurantResponse>);

  @override
  _i7.Future<_i4.SearchRestaurantResponse> getSearchRestaurant(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchRestaurant, [query]),
            returnValue: _i7.Future<_i4.SearchRestaurantResponse>.value(
              _FakeSearchRestaurantResponse_2(
                this,
                Invocation.method(#getSearchRestaurant, [query]),
              ),
            ),
          )
          as _i7.Future<_i4.SearchRestaurantResponse>);

  @override
  _i7.Future<_i5.AddReviewResponse> addReview(
    String? id,
    String? name,
    String? review,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addReview, [id, name, review]),
            returnValue: _i7.Future<_i5.AddReviewResponse>.value(
              _FakeAddReviewResponse_3(
                this,
                Invocation.method(#addReview, [id, name, review]),
              ),
            ),
          )
          as _i7.Future<_i5.AddReviewResponse>);
}
